"use strict";

const fs = require("node:fs");

const DEFAULT_MODEL = "gpt-5.5";
const DEFAULT_MAX_DIFF_FILES = 20;
const DEFAULT_MAX_DIFF_CHARS = 12000;

function getInput(name, fallback = "", env = process.env) {
  const key = `INPUT_${name.replace(/ /g, "_").replace(/-/g, "_").toUpperCase()}`;
  const value = env[key];
  return value === undefined || value === "" ? fallback : value;
}

function parseBoolean(value, fallback = false) {
  if (value === undefined || value === null || value === "") return fallback;
  return ["1", "true", "yes", "on"].includes(String(value).trim().toLowerCase());
}

function parseInteger(value, fallback) {
  const parsed = Number.parseInt(String(value), 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}

function truncate(text, maxChars) {
  const value = String(text || "");
  if (value.length <= maxChars) return value;
  return `${value.slice(0, maxChars)}\n\n...[truncated ${value.length - maxChars} chars]`;
}

function parseRepository(repository) {
  const [owner, repo] = String(repository || "").split("/");
  if (!owner || !repo) {
    throw new Error("GITHUB_REPOSITORY must be in the form owner/repo.");
  }
  return { owner, repo };
}

function readEvent(eventPath) {
  if (!eventPath) {
    throw new Error("GITHUB_EVENT_PATH is not set.");
  }
  return JSON.parse(fs.readFileSync(eventPath, "utf8"));
}

function detectMode(event, configuredMode = "auto") {
  if (configuredMode && configuredMode !== "auto") return configuredMode;
  if (event.pull_request) return "pull_request";
  if (event.issue && !event.issue.pull_request) return "issue";
  if (event.release) return "release";
  return "unknown";
}

function labelsFromIssue(issue) {
  return (issue.labels || []).map((label) => {
    if (typeof label === "string") return label;
    return label.name;
  }).filter(Boolean);
}

function suggestedIssueLabels(issue) {
  const text = `${issue.title || ""}\n${issue.body || ""}`.toLowerCase();
  const labels = new Set();

  const rules = [
    ["bug", /\b(bug|crash|error|exception|fail|failing|broken|regression)\b/],
    ["enhancement", /\b(feature|enhancement|request|proposal|support for|add)\b/],
    ["documentation", /\b(doc|docs|documentation|readme|example|guide)\b/],
    ["question", /\b(question|how do i|how to|help|usage)\b/],
    ["security", /\b(security|vulnerability|cve|xss|csrf|injection|secret|token)\b/],
    ["dependencies", /\b(dependency|dependencies|package|lockfile|npm|pip|cargo)\b/]
  ];

  for (const [label, pattern] of rules) {
    if (pattern.test(text)) labels.add(label);
  }

  if (labels.size === 0) labels.add("needs-triage");
  return Array.from(labels);
}

function missingIssueInformation(issue) {
  const text = `${issue.body || ""}`.toLowerCase();
  const missing = [];
  if (!/\b(version|commit|sha|release)\b/.test(text)) missing.push("affected version or commit");
  if (!/\b(reproduce|steps|expected|actual)\b/.test(text)) missing.push("clear reproduction steps");
  if (!/\b(os|node|python|browser|environment|platform)\b/.test(text)) missing.push("runtime or environment details");
  return missing;
}

function buildIssueReport(issue) {
  const existingLabels = labelsFromIssue(issue);
  const suggestedLabels = suggestedIssueLabels(issue);
  const missing = missingIssueInformation(issue);

  return [
    "## Maintainer-Bot Issue Triage",
    "",
    `**Issue:** #${issue.number} ${issue.title || ""}`,
    `**Current labels:** ${existingLabels.length ? existingLabels.join(", ") : "none"}`,
    `**Suggested labels:** ${suggestedLabels.join(", ")}`,
    "",
    "### Summary",
    truncate(issue.body || "No issue body provided.", 500),
    "",
    "### Maintainer Checklist",
    missing.length
      ? missing.map((item) => `- [ ] Ask for ${item}.`).join("\n")
      : "- [ ] Confirm scope and expected behavior.\n- [ ] Decide whether this needs a fix, docs update, or closure.",
    "",
    "_Generated by Maintainer-Bot._"
  ].join("\n");
}

function scorePullRequestRisk(files) {
  let score = 0;
  let signals = [];

  for (const file of files) {
    const name = file.filename || "";
    const patch = file.patch || "";
    const changes = Number(file.changes || 0);

    if (changes > 300) score += 2;
    if (changes > 80) score += 1;
    if (/\b(auth|login|permission|security|crypto|token|secret)\b/i.test(name)) {
      score += 3;
      signals.push(`security-sensitive path: ${name}`);
    }
    if (/\b(package-lock\.json|pnpm-lock\.yaml|yarn\.lock|requirements\.txt|go\.sum|Cargo\.lock)\b/i.test(name)) {
      score += 2;
      signals.push(`dependency lockfile changed: ${name}`);
    }
    if (/\b(migration|schema|database|db)\b/i.test(name)) {
      score += 2;
      signals.push(`data/schema path: ${name}`);
    }
    if (/^\+.*(eval\(|new Function|child_process|exec\(|spawn\()/m.test(patch)) {
      score += 3;
      signals.push(`potentially dangerous runtime call in ${name}`);
    }
  }

  const level = score >= 6 ? "high" : score >= 3 ? "medium" : "low";
  return { level, score, signals: Array.from(new Set(signals)) };
}

function summarizeChangedFiles(files, maxFiles = DEFAULT_MAX_DIFF_FILES) {
  return files.slice(0, maxFiles).map((file) => {
    const added = file.additions ?? 0;
    const removed = file.deletions ?? 0;
    const status = file.status || "modified";
    return `- ${file.filename} (${status}, +${added}/-${removed})`;
  }).join("\n");
}

function buildPullRequestReport(pullRequest, files, maxFiles = DEFAULT_MAX_DIFF_FILES) {
  const risk = scorePullRequestRisk(files);
  const totalChanges = files.reduce((sum, file) => sum + Number(file.changes || 0), 0);
  const truncatedNotice = files.length > maxFiles
    ? `\n\n_Note: showing ${maxFiles} of ${files.length} changed files._`
    : "";

  const riskSignals = risk.signals.length
    ? risk.signals.map((signal) => `- ${signal}`).join("\n")
    : "- No elevated risk signals found by deterministic checks.";

  return [
    "## Maintainer-Bot Pull Request Review",
    "",
    `**PR:** #${pullRequest.number} ${pullRequest.title || ""}`,
    `**Author:** ${pullRequest.user?.login || "unknown"}`,
    `**Risk level:** ${risk.level} (score ${risk.score})`,
    `**Changed files:** ${files.length}`,
    `**Total changes:** ${totalChanges}`,
    "",
    "### Changed Files",
    summarizeChangedFiles(files, maxFiles) || "- No file metadata available.",
    truncatedNotice,
    "",
    "### Risk Signals",
    riskSignals,
    "",
    "### Review Checklist",
    "- [ ] Confirm the behavior change is intentional.",
    "- [ ] Check that tests cover the changed behavior.",
    "- [ ] Review dependency, auth, security, and migration changes carefully.",
    "- [ ] Confirm release notes or docs are updated when user-facing behavior changes.",
    "",
    "_Generated by Maintainer-Bot._"
  ].join("\n");
}

function buildReleaseReport(release) {
  return [
    "## Maintainer-Bot Release Review",
    "",
    `**Release:** ${release.name || release.tag_name || "untitled"}`,
    `**Tag:** ${release.tag_name || "unknown"}`,
    `**Draft:** ${release.draft ? "yes" : "no"}`,
    `**Prerelease:** ${release.prerelease ? "yes" : "no"}`,
    "",
    "### Release Notes Preview",
    truncate(release.body || "No release notes provided.", 800),
    "",
    "### Maintainer Checklist",
    "- [ ] Confirm changelog covers user-facing changes.",
    "- [ ] Confirm compatibility and migration notes are included when needed.",
    "- [ ] Confirm artifacts, checksums, or package publishing steps completed successfully.",
    "- [ ] Confirm security fixes are clearly communicated without exposing sensitive details.",
    "",
    "_Generated by Maintainer-Bot._"
  ].join("\n");
}

function buildIssuePrompt(issue) {
  return [
    "You are assisting an open-source maintainer with issue triage.",
    "Return concise Markdown with these sections: Summary, Suggested labels, Missing information, Next maintainer action.",
    "",
    `Issue #${issue.number}: ${issue.title || ""}`,
    `Labels: ${labelsFromIssue(issue).join(", ") || "none"}`,
    "",
    "Body:",
    truncate(issue.body || "", 4000)
  ].join("\n");
}

function buildPullRequestPrompt(pullRequest, files, maxDiffChars = DEFAULT_MAX_DIFF_CHARS) {
  const diffContext = files.map((file) => {
    return [
      `File: ${file.filename}`,
      `Status: ${file.status || "modified"}, +${file.additions || 0}/-${file.deletions || 0}`,
      file.patch || "(patch unavailable)"
    ].join("\n");
  }).join("\n\n---\n\n");

  return [
    "You are assisting an open-source maintainer with a pull request review.",
    "Return concise Markdown with these sections: Summary, Risk level, Review checklist, Suggested tests, Release note impact.",
    "Do not approve or reject the PR. Keep the maintainer in control.",
    "",
    `PR #${pullRequest.number}: ${pullRequest.title || ""}`,
    `Author: ${pullRequest.user?.login || "unknown"}`,
    "",
    "Description:",
    truncate(pullRequest.body || "", 3000),
    "",
    "Changed files and diff context:",
    truncate(diffContext, maxDiffChars)
  ].join("\n");
}

function buildReleasePrompt(release) {
  return [
    "You are assisting an open-source maintainer with release preparation.",
    "Return concise Markdown with these sections: Release summary, Missing notes, Risk checklist, Suggested announcement.",
    "",
    `Release: ${release.name || release.tag_name || "untitled"}`,
    `Tag: ${release.tag_name || "unknown"}`,
    "",
    "Release body:",
    truncate(release.body || "", 5000)
  ].join("\n");
}

function extractOpenAIText(payload) {
  if (payload.output_text) return payload.output_text;
  const chunks = [];
  for (const item of payload.output || []) {
    for (const content of item.content || []) {
      if (content.text) chunks.push(content.text);
      if (content.type === "output_text" && content.text) chunks.push(content.text);
    }
  }
  return chunks.join("\n").trim();
}

async function requestOpenAISummary({ apiKey, model, prompt }) {
  const response = await fetch("https://api.openai.com/v1/responses", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${apiKey}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      model,
      input: prompt,
      max_output_tokens: 1200
    })
  });

  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    const message = payload.error?.message || response.statusText;
    throw new Error(`OpenAI request failed: ${message}`);
  }

  const text = extractOpenAIText(payload);
  if (!text) throw new Error("OpenAI response did not include text output.");
  return `${text}\n\n_Generated by Maintainer-Bot._`;
}

class GitHubClient {
  constructor({ token, owner, repo, apiUrl = "https://api.github.com" }) {
    this.token = token;
    this.owner = owner;
    this.repo = repo;
    this.apiUrl = apiUrl.replace(/\/$/, "");
  }

  async request(method, route, body) {
    const headers = {
      "Accept": "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28"
    };
    if (this.token) headers.Authorization = `Bearer ${this.token}`;
    if (body !== undefined) headers["Content-Type"] = "application/json";

    const response = await fetch(`${this.apiUrl}${route}`, {
      method,
      headers,
      body: body === undefined ? undefined : JSON.stringify(body)
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`GitHub API ${method} ${route} failed: ${response.status} ${text}`);
    }

    if (response.status === 204) return null;
    return response.json();
  }

  async fetchPullFiles(number, maxFiles) {
    const files = [];
    let page = 1;
    while (files.length < maxFiles) {
      const remaining = Math.min(100, maxFiles - files.length);
      const route = `/repos/${this.owner}/${this.repo}/pulls/${number}/files?per_page=${remaining}&page=${page}`;
      const batch = await this.request("GET", route);
      files.push(...batch);
      if (batch.length < remaining) break;
      page += 1;
    }
    return files;
  }

  async createIssueComment(number, body) {
    return this.request("POST", `/repos/${this.owner}/${this.repo}/issues/${number}/comments`, { body });
  }
}

function writeFileAppend(path, content) {
  if (!path) return;
  fs.appendFileSync(path, content, "utf8");
}

function writeOutput(name, value, env = process.env) {
  const outputPath = env.GITHUB_OUTPUT;
  if (!outputPath) return;
  const delimiter = `maintainer_bot_${Date.now()}_${Math.random().toString(16).slice(2)}`;
  writeFileAppend(outputPath, `${name}<<${delimiter}\n${value}\n${delimiter}\n`);
}

function writeStepSummary(report, env = process.env) {
  if (!env.GITHUB_STEP_SUMMARY) return;
  writeFileAppend(env.GITHUB_STEP_SUMMARY, `${report}\n`);
}

function readConfig(env = process.env) {
  return {
    githubToken: getInput("github-token", env.GITHUB_TOKEN || "", env),
    openaiApiKey: getInput("openai-api-key", "", env),
    model: getInput("model", DEFAULT_MODEL, env),
    mode: getInput("mode", "auto", env),
    dryRun: parseBoolean(getInput("dry-run", "true", env), true),
    postComment: parseBoolean(getInput("post-comment", "false", env), false),
    maxDiffFiles: parseInteger(getInput("max-diff-files", String(DEFAULT_MAX_DIFF_FILES), env), DEFAULT_MAX_DIFF_FILES),
    maxDiffChars: parseInteger(getInput("max-diff-chars", String(DEFAULT_MAX_DIFF_CHARS), env), DEFAULT_MAX_DIFF_CHARS),
    eventPath: env.GITHUB_EVENT_PATH,
    repository: env.GITHUB_REPOSITORY,
    apiUrl: env.GITHUB_API_URL || "https://api.github.com"
  };
}

async function buildReport({ event, mode, config, github }) {
  if (mode === "issue") {
    const fallback = buildIssueReport(event.issue);
    if (config.openaiApiKey && !config.dryRun) {
      return requestOpenAISummary({
        apiKey: config.openaiApiKey,
        model: config.model,
        prompt: buildIssuePrompt(event.issue)
      }).catch((error) => `${fallback}\n\n> AI-assisted summary failed: ${error.message}`);
    }
    return fallback;
  }

  if (mode === "pull_request") {
    const files = await github.fetchPullFiles(event.pull_request.number, config.maxDiffFiles);
    const fallback = buildPullRequestReport(event.pull_request, files, config.maxDiffFiles);
    if (config.openaiApiKey && !config.dryRun) {
      return requestOpenAISummary({
        apiKey: config.openaiApiKey,
        model: config.model,
        prompt: buildPullRequestPrompt(event.pull_request, files, config.maxDiffChars)
      }).catch((error) => `${fallback}\n\n> AI-assisted summary failed: ${error.message}`);
    }
    return fallback;
  }

  if (mode === "release") {
    const fallback = buildReleaseReport(event.release);
    if (config.openaiApiKey && !config.dryRun) {
      return requestOpenAISummary({
        apiKey: config.openaiApiKey,
        model: config.model,
        prompt: buildReleasePrompt(event.release)
      }).catch((error) => `${fallback}\n\n> AI-assisted summary failed: ${error.message}`);
    }
    return fallback;
  }

  return [
    "## Maintainer-Bot",
    "",
    "No supported GitHub event was detected.",
    "",
    "_Generated by Maintainer-Bot._"
  ].join("\n");
}

async function main() {
  const config = readConfig();
  const event = readEvent(config.eventPath);
  const mode = detectMode(event, config.mode);
  const { owner, repo } = parseRepository(config.repository);
  const github = new GitHubClient({
    token: config.githubToken,
    owner,
    repo,
    apiUrl: config.apiUrl
  });

  const report = await buildReport({ event, mode, config, github });
  const commentTarget = event.issue?.number || event.pull_request?.number;

  if (config.postComment && !config.dryRun && commentTarget && ["issue", "pull_request"].includes(mode)) {
    await github.createIssueComment(commentTarget, report);
  }

  writeStepSummary(report);
  writeOutput("summary", report);
  writeOutput("mode", mode);
  console.log(report);
}

if (require.main === module) {
  main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}

module.exports = {
  buildIssueReport,
  buildPullRequestPrompt,
  buildPullRequestReport,
  buildReleaseReport,
  detectMode,
  extractOpenAIText,
  missingIssueInformation,
  parseBoolean,
  parseInteger,
  scorePullRequestRisk,
  suggestedIssueLabels,
  truncate
};
